services:
  postgres:
    image: postgres:16.2-alpine3.19
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    container_name: arch-unit-rules-postgres
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 3s
      timeout: 20s
      retries: 3
      start_period: 10s

volumes:
  postgres-storage:
